<h1> Комментарий ревьюера </h1>

Привет, Дарья!
Меня зовут Виктория Ильина, и я буду проверять твой проект. Предлагаю общаться на "ты", но если тебе будет не комфортно, обязательно сообщи и мы перейдем на "вы". 

Моя основная цель - не указать на совершённые тобой ошибки, а поделиться своим опытом и помочь тебе стать специалистом по Data Science. Ты уже проделала большую работу над проектом, но давай сделаем его ещё лучше. Ниже ты найдёшь мои комментарии - пожалуйста, не перемещай, не изменяй и не удаляй их. Я буду использовать различные цвета, чтобы было легче воспринимать мои комментарии:

<div class="alert alert-block alert-danger">
<b>Комментарий ревьюера❌:</b> Так выделены самые важные замечания. Без их отработки проект не будет принят.
</div>

<div class="alert alert-block alert-warning">
<b>Комментарий ревьюера🤔:</b> Так выделены небольшие замечания. Одно-два таких замечания в проекте допустимы, но если их будет больше - тебе будет необходимо внести исправления. Однако, если перед нами стоит цель не просто сдать проект и забыть, а приобрести новые знания и успешно применять их в будущем, я бы всё-таки рекомендовала тебе прорабатывать эти недочёты.
</div>
    
<div class="alert alert-block alert-success">
<b>Комментарий ревьюера👍:</b> Так я выделю все остальные комментарии.
</div>
    
Давай работать над проектом в диалоге: если ты что-то меняешь в проекте или отвечаешь на мои комментарии - пиши об этом. Мне будет легче отследить изменения, если ты выделишь свои комментарии:

<div class="alert alert-block alert-info">
<b>Комментарий студента:</b> Например, вот так.
</div>

Давай посмотрим, что получилось!

<h1>Содержание<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Загрузка-данных" data-toc-modified-id="Загрузка-данных-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Загрузка данных</a></span></li><li><span><a href="#Умножение-матриц" data-toc-modified-id="Умножение-матриц-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>Умножение матриц</a></span></li><li><span><a href="#Алгоритм-преобразования" data-toc-modified-id="Алгоритм-преобразования-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>Алгоритм преобразования</a></span></li><li><span><a href="#Проверка-алгоритма" data-toc-modified-id="Проверка-алгоритма-4"><span class="toc-item-num">4&nbsp;&nbsp;</span>Проверка алгоритма</a></span><ul class="toc-item"><li><span><a href="#Создание-обратимой-матрицы" data-toc-modified-id="Создание-обратимой-матрицы-4.1"><span class="toc-item-num">4.1&nbsp;&nbsp;</span>Создание обратимой матрицы</a></span></li><li><span><a href="#Модель-на-исходных-данных" data-toc-modified-id="Модель-на-исходных-данных-4.2"><span class="toc-item-num">4.2&nbsp;&nbsp;</span>Модель на исходных данных</a></span></li><li><span><a href="#Модель-на-преобразованных-данных" data-toc-modified-id="Модель-на-преобразованных-данных-4.3"><span class="toc-item-num">4.3&nbsp;&nbsp;</span>Модель на преобразованных данных</a></span></li></ul></li><li><span><a href="#Вывод" data-toc-modified-id="Вывод-5"><span class="toc-item-num">5&nbsp;&nbsp;</span>Вывод</a></span></li><li><span><a href="#Чек-лист-проверки" data-toc-modified-id="Чек-лист-проверки-6"><span class="toc-item-num">6&nbsp;&nbsp;</span>Чек-лист проверки</a></span></li></ul></div>

# Защита персональных данных клиентов

Вам нужно защитить данные клиентов страховой компании «Хоть потоп». Разработайте такой метод преобразования данных, чтобы по ним было сложно восстановить персональную информацию. Обоснуйте корректность его работы.

Нужно защитить данные, чтобы при преобразовании качество моделей машинного обучения не ухудшилось. Подбирать наилучшую модель не требуется.

## Загрузка данных

In [1]:
# импортирование библиотек
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score
from sklearn.linear_model import LinearRegression

In [2]:
# чтение данных из файла
data = pd.read_csv('/datasets/insurance.csv')
# просмотр первых десяти строчек в таблице 
data.head(10)

Пол  Возраст  Зарплата  Члены семьи  Страховые выплаты
0    1     41.0   49600.0            1                  0
1    0     46.0   38000.0            1                  1
2    0     29.0   21000.0            0                  0
3    0     21.0   41700.0            2                  0
4    1     28.0   26100.0            0                  0
5    1     43.0   41000.0            2                  1
6    1     39.0   39700.0            2                  0
7    1     25.0   38600.0            4                  0
8    1     36.0   49700.0            1                  0
9    1     32.0   51700.0            1                  0

In [3]:
# вывод информации о таблице
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   Пол                5000 non-null   int64  
 1   Возраст            5000 non-null   float64
 2   Зарплата           5000 non-null   float64
 3   Члены семьи        5000 non-null   int64  
 4   Страховые выплаты  5000 non-null   int64  
dtypes: float64(2), int64(3)
memory usage: 195.4 KB


In [4]:
data.describe()

Пол      Возраст      Зарплата  Члены семьи  Страховые выплаты
count  5000.000000  5000.000000   5000.000000  5000.000000        5000.000000
mean      0.499000    30.952800  39916.360000     1.194200           0.148000
std       0.500049     8.440807   9900.083569     1.091387           0.463183
min       0.000000    18.000000   5300.000000     0.000000           0.000000
25%       0.000000    24.000000  33300.000000     0.000000           0.000000
50%       0.000000    30.000000  40200.000000     1.000000           0.000000
75%       1.000000    37.000000  46600.000000     2.000000           0.000000
max       1.000000    65.000000  79000.000000     6.000000           5.000000

In [25]:
data.corr()

Пол   Возраст  Зарплата  Члены семьи  \
Пол                1.000000  0.001953  0.015456    -0.007315   
Возраст            0.001953  1.000000 -0.017386    -0.009064   
Зарплата           0.015456 -0.017386  1.000000    -0.031687   
Члены семьи       -0.007315 -0.009064 -0.031687     1.000000   
Страховые выплаты  0.011565  0.654964 -0.013123    -0.039303   

                   Страховые выплаты  
Пол                         0.011565  
Возраст                     0.654964  
Зарплата                   -0.013123  
Члены семьи                -0.039303  
Страховые выплаты           1.000000

In [5]:
# смена типа данных в столбце возраст и зарплата
data['Возраст'] = data['Возраст'].astype(int)
data['Зарплата'] = data['Зарплата'].astype(int)

In [6]:
# подсчёт явных дубликатов
print(data.duplicated().sum())

153


In [7]:
# удаление дубликатов
data = data.drop_duplicates(keep='first')
# повторный подсчёт явных дубликатов
print(data.duplicated().sum())

0


Данные состоят из четырех категорий (столбцов). Они были приведены мною к типу int. Явные дубликаты были удалены, неявных нет. Пропусков в данных нет. 

<div class="alert alert-block alert-success">
<b>Комментарий ревьюера👍:</b> Отлично!
    
Этого не было в требованиях к проекту, просто дополнительно по EDA:
    
Если использовать функцию describe(), то можно увидеть, что в таблице данных компании соблюден почти идеальный баланс между мужчинами и женщинами. Средний возраст застрахованного составляет около 31 года, при этом медиана составляет 30. Границы возраста застрахованных приводят к выводу, что компания не занимается страхованием лиц, чей возраст составляет менее 18 и старше 65 лет. Также интересно взглянуть на уровень заработной платы застрахованных - медиана составляет чуть более 40 000 рублей. В целом, в компании скорее представлен средний экономический класс, чем слишком бедные или слишком богатые граждане. 
    
Дополнительно можно было бы посмотреть корреляцию. Возраст и количество страховых выплат клиенту за последние 5 лет имеют корреляцию 0.651. Вероятно, для компании есть взаимосвязь: чем старше застрахованное лицо, тем более вероятно он потребует страховку чаще, следовательно, несёт в себе больше рисков для предприятия.
</div>


<div class="alert alert-block alert-info">
<b>Комментарий студентки:</b> Поняла, добавила.
</div>

## Умножение матриц

В этом задании вы можете записывать формулы в *Jupyter Notebook.*

Чтобы записать формулу внутри текста, окружите её символами доллара \\$; если снаружи —  двойными символами \\$\\$. Эти формулы записываются на языке вёрстки *LaTeX.* 

Для примера мы записали формулы линейной регрессии. Можете их скопировать и отредактировать, чтобы решить задачу.

Работать в *LaTeX* необязательно.

Обозначения:

- $X$ — матрица признаков (нулевой столбец состоит из единиц)

- $y$ — вектор целевого признака

- $P$ — матрица, на которую умножаются признаки

- $w$ — вектор весов линейной регрессии (нулевой элемент равен сдвигу)

Предсказания:

$$
a = Xw
$$

Задача обучения:

$$
w = \arg\min_w MSE(Xw, y)
$$

Формула обучения:

$$
w = (X^T X)^{-1} X^T y
$$

**Ответ:** Не изменится

**Обоснование:** 

**Для матрицы X:**

$$
a = Xw
$$

$$
w = (X^T X)^{-1} X^T y
$$

**Для матрицы XP:**

$$
a_1 = XPw_1
$$

$$
w_1 = ((XP)^T XP)^{-1} (XP)^T y
$$

Применим свойтсво

$$
(AB)^T = B^T A^T
$$

$$
w_1 = (P^T X^T XP)^{-1} P^T X^T y
$$

Применим свойтсво

$$
(AB)^{-1} = B^{-1} A^{-1}
$$

$$
w_1 = P^{-1} (X^T X)^{-1} (P^T)^{-1} P^T X^T y
$$

$$
w_1 = P^{-1} (X^T X)^{-1} X^T y
$$

Подставим

$$
a_1 = XPP^{-1} (X^T X)^{-1} X^T y
$$

$$
a_1 = X(X^T X)^{-1} X^T y
$$

$$
a_1 = a
$$


<div class="alert alert-block alert-warning">
<b>Комментарий ревьюера🤔:</b> Абсолютно верно, молодец, что не раскрыла $(X^T X)^{-1}$, так как для неквадратных матриц $X$ и $X^T$ обратных матриц не существует. Единственная придирка, чтобы w1 выглядело как $w_1$ нужно добавить нижнее подчеркивание =)
</div>

<div class="alert alert-block alert-info">
<b>Комментарий студентки:</b> Не знала, подправила.
</div>

## Алгоритм преобразования

**Алгоритм**

Признаки можно умножить на рандомно созданную обратимую матрицу. Таким образом данные будут отличны от исходных.

**Обоснование**

Подобрать обратимую матрицу будет крайне сложно, так как она заполнена случайными числами. Но мы, зная обратимую матрицу, сможем найти ей парную и восстановить исходные данные.

## Проверка алгоритма

### Создание обратимой матрицы

In [8]:
# создание пустой матрицы подходящей по размеру к признакам для умножения
random_array = np.zeros((data.shape[1], data.shape[1]))
random_array

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [9]:
# заполнение матрицы
random_array[:, 0] = np.random.randint(2, size=(data.shape[1]))
random_array

array([[0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [10]:
print(data['Возраст'].min())
print(data['Возраст'].max())
random_array[:, 1] = np.random.randint(18, 66, size=(data.shape[1]))
random_array

18
65


array([[ 0., 47.,  0.,  0.,  0.],
       [ 1., 41.,  0.,  0.,  0.],
       [ 0., 30.,  0.,  0.,  0.],
       [ 0., 18.,  0.,  0.,  0.],
       [ 0., 57.,  0.,  0.,  0.]])

In [11]:
print(data['Зарплата'].min())
print(data['Зарплата'].max())
random_array[:, 2] = np.random.randint(5300, 79001, size=(data.shape[1]))
random_array

5300
79000


array([[0.0000e+00, 4.7000e+01, 7.0212e+04, 0.0000e+00, 0.0000e+00],
       [1.0000e+00, 4.1000e+01, 6.0186e+04, 0.0000e+00, 0.0000e+00],
       [0.0000e+00, 3.0000e+01, 4.3779e+04, 0.0000e+00, 0.0000e+00],
       [0.0000e+00, 1.8000e+01, 5.6803e+04, 0.0000e+00, 0.0000e+00],
       [0.0000e+00, 5.7000e+01, 7.3142e+04, 0.0000e+00, 0.0000e+00]])

In [12]:
print(data['Члены семьи'].min())
print(data['Члены семьи'].max())
random_array[:, 3] = np.random.randint(7, size=(data.shape[1]))
random_array

0
6


array([[0.0000e+00, 4.7000e+01, 7.0212e+04, 3.0000e+00, 0.0000e+00],
       [1.0000e+00, 4.1000e+01, 6.0186e+04, 3.0000e+00, 0.0000e+00],
       [0.0000e+00, 3.0000e+01, 4.3779e+04, 2.0000e+00, 0.0000e+00],
       [0.0000e+00, 1.8000e+01, 5.6803e+04, 4.0000e+00, 0.0000e+00],
       [0.0000e+00, 5.7000e+01, 7.3142e+04, 2.0000e+00, 0.0000e+00]])

In [13]:
print(data['Страховые выплаты'].min())
print(data['Страховые выплаты'].max())
random_array[:, 4] = np.random.randint(6, size=(data.shape[1]))
random_array

0
5


array([[0.0000e+00, 4.7000e+01, 7.0212e+04, 3.0000e+00, 3.0000e+00],
       [1.0000e+00, 4.1000e+01, 6.0186e+04, 3.0000e+00, 4.0000e+00],
       [0.0000e+00, 3.0000e+01, 4.3779e+04, 2.0000e+00, 2.0000e+00],
       [0.0000e+00, 1.8000e+01, 5.6803e+04, 4.0000e+00, 2.0000e+00],
       [0.0000e+00, 5.7000e+01, 7.3142e+04, 2.0000e+00, 3.0000e+00]])

In [14]:
# преобразование признаков
encrypted_data = np.array(data) @ random_array
encrypted_data = encrypted_data.round()
encrypted_data = encrypted_data.astype(int)
encrypted_data = pd.DataFrame(encrypted_data, columns=data.columns)
encrypted_data

Пол  Возраст    Зарплата  Члены семьи  Страховые выплаты
0      41  1489746  2174033041        99330              99369
1      46  1141961  1666500501        76144              76189
2      29   631189   921104394        42087              42116
3      21  1251897  1826961812        83471              83488
4      28   784195  1144387320        52287              52315
...   ...      ...         ...          ...                ...
4842   28  1072184  1564709114        71492              71516
4843   34  1573412  2296122727       104906             104938
4844   20  1017856  1485425426        67868              67884
4845   22   982003  1433138013        65481              65497
4846   28  1219213  1779239623        81291              81317

[4847 rows x 5 columns]

In [15]:
# восстановление признаков 
decrypted_data = np.array(encrypted_data) @ np.linalg.inv(random_array)
decrypted_data = pd.DataFrame(decrypted_data, columns=data.columns)
decrypted_data = decrypted_data.round()
decrypted_data = decrypted_data.astype(int)
decrypted_data

Пол  Возраст  Зарплата  Члены семьи  Страховые выплаты
0       1       41     49600            1                  0
1       0       46     38000            1                  1
2       0       29     21000            0                  0
3       0       21     41700            2                  0
4       1       28     26100            0                  0
...   ...      ...       ...          ...                ...
4842    0       28     35700            2                  0
4843    0       34     52400            1                  0
4844    0       20     33900            2                  0
4845    1       22     32700            3                  0
4846    1       28     40600            1                  0

[4847 rows x 5 columns]

In [16]:
data

Пол  Возраст  Зарплата  Члены семьи  Страховые выплаты
0       1       41     49600            1                  0
1       0       46     38000            1                  1
2       0       29     21000            0                  0
3       0       21     41700            2                  0
4       1       28     26100            0                  0
...   ...      ...       ...          ...                ...
4995    0       28     35700            2                  0
4996    0       34     52400            1                  0
4997    0       20     33900            2                  0
4998    1       22     32700            3                  0
4999    1       28     40600            1                  0

[4847 rows x 5 columns]

Приобразование признаков сделано и проверено, что можно восстановить исходные признаки

### Модель на исходных данных

In [17]:
# создание выборок
features = data.drop(['Страховые выплаты'], axis=1)
target = data['Страховые выплаты']

In [18]:
# создание модели
model = LinearRegression()
# обучение модели
model.fit(features, target)
# предсказания модели
predictions = model.predict(features)
# оценивание модели
print('Метрика R2 модели:', r2_score(target, predictions))

Метрика R2 модели: 0.4302010046633359


### Модель на преобразованных данных

In [19]:
# создание выборок
encrypted_features = encrypted_data.drop(['Страховые выплаты'], axis=1)
encrypted_target = encrypted_data['Страховые выплаты']

In [20]:
# создание модели
model = LinearRegression()
# обучение модели
model.fit(encrypted_features, encrypted_target)
# предсказания модели
predictions = model.predict(encrypted_features)
# оценивание модели
print('Метрика R2 модели:', r2_score(encrypted_target, predictions))

Метрика R2 модели: 0.9999999999999937


Я не понимаю, где ошибка, что модель начала выдавать такие результаты.

<div class="alert alert-block alert-warning">
<b>Комментарий ревьюера🤔:</b> Мне кажется ты очень сильно перемудрила в части 4.1, всё можно сделать гораздо проще, смотри ниже =)
</div>

<div class="alert alert-block alert-info">
<b>Комментарий студентки:</b> Все понятно, кроме почему не надо умножать целевой признак на обратимую матрицу?
</div>

<div class="alert alert-block alert-success">
<b>Комментарий ревьюера V.2👍:</b> Я тебе в слак скинула картинку посмотри почему =)
</div>

In [21]:
#KОД РЕВЬЮЕРА
# создаем матрицу перехода
np.random.seed(0)
n, m = data.shape
matrix = np.random.rand(m-1, m-1)

# создание выборок
features = data.drop(['Страховые выплаты'], axis=1)
target = data['Страховые выплаты']

# делим выборки на трейн и тест
X_train, X_test, y_train, y_test = train_test_split( features, target, random_state = 42)

# кодируем признаки в трейне и тесте
X_train_encoded = X_train @ matrix
X_test_encoded = X_test @ matrix

In [22]:
#KОД РЕВЬЮЕРА
# строим линейную регрессию для незакодированных признаков
model = LinearRegression().fit(X_train, y_train)
predictions = model.predict(X_test)
print(r2_score(y_test, predictions))

0.44346331080942536


In [23]:
#KОД РЕВЬЮЕРА
# строим линейную регрессию для закодированных признаков
model = LinearRegression().fit(X_train_encoded, y_train)
predictions = model.predict(X_test_encoded)
print(r2_score(y_test, predictions))

0.4434633108088576


## Вывод

Мною были исследованы данные клиентов страховой компании. Над ними я провела предобработку. 

Был найден алгоритм преобразования данных в целях защиты данных клиентов. Этим алгоритмом является умножение исходных данных, представленный в виде матрицы, на обратимую матрицу, заполненную случайнями числами. Таким образом данные будут отличны от исходных. Подобрать обратимую матрицу будет крайне сложно, так как она заполнена случайными числами. Но мы, зная обратимую матрицу, сможем найти ей парную и восстановить исходные данные. Математически было доказано, что качество модели не ухудшится. На практике это тоже было опробовано: обучила дваждый модель на исходных и приобразованных данных. Качество модели не изменилось. 

## Чек-лист проверки

Поставьте 'x' в выполненных пунктах. Далее нажмите Shift+Enter.

- [x]  Jupyter Notebook открыт
- [ ]  Весь код выполняется без ошибок
- [ ]  Ячейки с кодом расположены в порядке исполнения
- [ ]  Выполнен шаг 1: данные загружены
- [ ]  Выполнен шаг 2: получен ответ на вопрос об умножении матриц
    - [ ]  Указан правильный вариант ответа
    - [ ]  Вариант обоснован
- [ ]  Выполнен шаг 3: предложен алгоритм преобразования
    - [ ]  Алгоритм описан
    - [ ]  Алгоритм обоснован
- [ ]  Выполнен шаг 4: алгоритм проверен
    - [ ]  Алгоритм реализован
    - [ ]  Проведено сравнение качества моделей до и после преобразования

<div class="alert alert-block alert-warning">
<b>Комментарий ревьюера🤔:</b> Спасибо тебе за проделанную работу, ты немного перемудрила в блоке 4, посмотри, пожалуйста, моё решение и добавь вывод. До скорой встречи =)
</div>

<div class="alert alert-block alert-success">
<b>Комментарий ревьюера V.2👍:</b> 

Обзоры по применению криптографии в машинном обучении: https://arxiv.org/pdf/1902.04109.pdf, https://www.researchgate.net/publication/342746786_Some_Applications_of_Machine_Learning_in_Cryptography
   
Примеры использования линейной алгебры в машинном обучении:
https://machinelearningmastery.com/examples-of-linear-algebra-in-machine-learning/
    
Для чего нужна математика в машинном обучении?
https://proglib.io/p/dlya-chego-nuzhen-matematicheskiy-analiz-v-mashinnom-obuchenii-2021-02-15

Большая статья по векторам:
https://neptune.ai/blog/understanding-vectors-from-a-machine-learning-perspective  
    
Удачи в будущих проектах и работе =)
    
</div>
